# -*- coding: utf-8 -*-
"""dp_pgm_minutemen_istat_synt_challenge.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NhUZjNkURG4JLftXmcvAp3U3iYyN6-ft

# All imports
"""

import os
os.system('pip install numpy')
os.system('pip install gdown')
os.system('pip install jsonschema')
import platform
import numpy
import pandas
# Operating System
OS = platform.system()                                                             # returns 'Windows', 'Linux', etc

"""# All Globals"""

benchmark = False

"""# All Program checks"""

os.system('python --version')
print(numpy.__version__)
print(pandas.__version__)

"""# All Updates"""

'''
if colab 
  #install python 3.9
  !sudo apt-get update -y
  !sudo apt-get install python3.9

  #change alternatives
  !sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
  !sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2

  #check python version
  !python --version
  #3.9.6
'''

"""# Libraries Installation Section

Installation of all required libraries: private-pgm and nist-synthetic-data
"""

os.system('git clone https://github.com/ryan112358/private-pgm.git')

os.system('pip install -r ./private-pgm/requirements.txt')
os.system('pip install ./private-pgm')

os.system('git clone https://github.com/ryan112358/nist-synthetic-data-2021.git')

os.system('pip install -r ./nist-synthetic-data-2021/requirements.txt')

"""# Data Download - ACS and SatGPA"""

if benchmark == True: 
  if not os.path.exists("./adult.csv"):
      os.system('gdown --id "1pvGlZG0ypswgey-rzvxdZev5F-PYnHVz" --output "./adult.csv"')
else: 
  if not os.path.exists("./satgpa.csv"):
      os.system('gdown --id "1NNVF1LhBDkW_KKp5_QW8cAiQDFatzWMy" --output "./satgpa.csv"')

  '''
  if not os.path.exists("./acs_dataset.zip"):
      os.system('gdown --id "1mKZfDieGBJP-cS-R7_i3zVKVawXThfUc" --output "./acs_dataset.zip"')
      if OS == "Linux":
          os.system('unzip -o -n "./acs_dataset.zip" -d "./"')
  '''

  if not os.path.exists("./satgpa_parameters.json"):
      os.system('gdown --id "1sA-sWA8WktSM1yfvY0ceg5woaVyIFyfs" --output "./satgpa_parameters.json"')

"""# Schema Generation via Schemagen"""

if benchmark == True: 
  os.system('python ./nist-synthetic-data-2021/extensions/schemagen.py ./adult.csv --max_categorical 40')
  #!python ./nist-synthetic-data-2021/extensions/schemagen.py /content/nist-synthetic-data-2021/extensions/datasets/raw/adult.csv --max_categorical 40
else:
  os.system('python ./nist-synthetic-data-2021/extensions/schemagen.py ./satgpa.csv --max_categorical 100')
  #!python ./nist-synthetic-data-2021/extensions/schemagen.py ./satgpa.csv --max_categorical 100

"""# Data Discretization via Schemagen"""

os.system('python ./nist-synthetic-data-2021/extensions/transform.py --transform discretize --df "./satgpa.csv" --schema "./satgpa_parameters.json" --output_dir "./"')
#!python ./nist-synthetic-data-2021/extensions/transform.py --transform discretize --df "./satgpa.csv" --schema "./satgpa_parameters.json" --output_dir "./"

os.system('python ./nist-synthetic-data-2021/extensions/check_domain.py --dataset "./discretized.csv" --domain "./domain.json"')

"""# Synthetization of Input Discretized Data"""

os.system('python ./nist-synthetic-data-2021/extensions/adaptive_grid.py --dataset "./discretized.csv" --domain "./domain.json" --save "./satgpa_discretized_synthetic.csv" --epsilon 10')
#!python ./nist-synthetic-data-2021/extensions/adaptive_grid.py --dataset "./discretized.csv" --domain "./domain.json" --save "./satgpa_discretized_synthetic.csv" --epsilon 10

os.system('python ./nist-synthetic-data-2021/extensions/transform.py --transform undo_discretize --df "./satgpa_discretized_synthetic.csv" --schema "./satgpa_parameters.json"')
#!python ./nist-synthetic-data-2021/extensions/transform.py --transform undo_discretize --df "./" --schema "./satgpa_parameters.json"